version: 2
updates:
  # Enable version updates for npm in each plugin directory
  - package-ecosystem: "npm"
    directory: "/foxel-image-viewer"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "maxage"
    assignees:
      - "maxage"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Ignore major version updates for now
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
