name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        plugin: [
          'foxel-image-viewer'
        ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ matrix.plugin }}/package-lock.json
        
    - name: Install dependencies
      run: |
        cd ${{ matrix.plugin }}
        npm ci
        
    - name: Type check
      run: |
        cd ${{ matrix.plugin }}
        npx tsc --noEmit
        
    - name: Build test
      run: |
        cd ${{ matrix.plugin }}
        npm run build
        
    - name: Check build output
      run: |
        cd ${{ matrix.plugin }}
        if [ -f "dist/plugin.js" ]; then
          echo "✅ Build successful for ${{ matrix.plugin }}"
          echo "📊 File size: $(du -h dist/plugin.js | cut -f1)"
        else
          echo "❌ Build failed for ${{ matrix.plugin }}"
          exit 1
        fi
