name: Simple Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install and build foxel-image-viewer
      run: |
        cd foxel-image-viewer
        npm install
        npm run build
        
    - name: Check build output
      run: |
        cd foxel-image-viewer
        if [ -f "dist/plugin.js" ]; then
          echo "✅ Build successful"
          echo "📊 File size: $(du -h dist/plugin.js | cut -f1)"
          ls -la dist/
        else
          echo "❌ Build failed"
          exit 1
        fi
